### ISSUE TITLE
Show Reference time or offset to give "last contact" a context

### ISSUE THREAD

**Issue by jongleur1983** [osmfoundation/osmf-server-info#12]
The "Last Contact" column only shows a time in a (without deeper knowledge) unknown timezone.
For me the last contact to any server is roughly 3 hours ago, but how much is due to my different time zone?

I therefore suggest to add "now" in the local reference time to the page output.
This could be either on top of the page or, probably even better, an additional column could show the offset between "now" and the last contact.

Unfortunately I don't understand the code, so I've to leave that here as a suggestion and idea.

**Comment by tomhughes** [comment]
The time will be UTC I expect, as all our servers run on UTC. Not sure what you think adding "now" will do exactly.

Any live machine should have a last contact time within the last hour (in the UTC time zone).

But really those times are just a debugging aid for me to be able to see if a machine is live or not ;-)

**Comment by Firefishy** [comment]
We now include "Last updated" in the footer.
