### ISSUE TITLE
katla description on hardware page and in osm wiki

### ISSUE THREAD

**Issue by dieterdreist** [osmfoundation/osmf-server-info#14]
On https://hardware.openstreetmap.org/servers/katla.openstreetmap.org/ it states:
"Read only database mirror for www.openstreetmap.org"
in the wiki: https://wiki.openstreetmap.org/wiki/Servers#Imperial_-_In_Use
Katla "Master DB server"

**Comment by tomhughes** [comment]
Wiki wrong. Film at eleven.

**Comment by Firefishy** [comment]
I have now removed the out-of-date hardware table from the wiki. The http://hardware.openstreetmap.org link remains.
