### ISSUE TITLE
Move to OpenStreetMap organisation?

### ISSUE THREAD

**Issue by Firefishy** [osmfoundation/osmf-server-info#29]
@gravitystorm would you be ok if we moved this to the github.com/OpenStreetMap organisation?

It allows easier management of any potential github action runners, maintainer admin and security requirements (e.g. 2FA).

**Comment by gravitystorm** [comment]
Sure, happy for it to me moved wherever. If you need me to do it, let me know.

I think for a repo with osmf in the name, https://github.com/osmfoundation/ might also be appropriate? I'll leave that to others  e.g. OWG to decide though.

**Comment by Firefishy** [comment]
@gravitystorm Set temporary owner permission for https://github.com/osmfoundation , you should see an invite link at top of that link. (or via email)

Please could you transfer the repo when you have a chance? Docs are here: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by gravitystorm** [comment]
Done. There wasn't an OWG or sysadmins team in the org, so I didn't add any teams to the repo while transferring.
