### ISSUE TITLE
Find replacement URLs for Intel SSDs

### ISSUE THREAD

**Issue by pnorman** [osmfoundation/osmf-server-info#42]
Intel sold their SSD division sometime back, now all the ark.intel.com links for their SSDs are 404 pages. Replacement links are needed, or if none can be found, the links should be removed.

**Comment by tomhughes** [comment]
They sold it to hynix but they don't seem to have any information on the old Intel products anywhere on their site.

**Comment by Firefishy** [comment]
archive.org? ;-)
