### ISSUE TITLE
RAM doesn't add up

### ISSUE THREAD

**Issue by pnorman** [osmfoundation/osmf-server-info#5]
[orm](https://hardware.openstreetmap.org/servers/orm.openstreetmap.org/) is listed as having
- 79GB Total
- 4 x 16GB 1333 MHz Other DIMM
- 4 x 4GB 1333 MHz Other DIMM
- 4 x Spare DIMM slot

The DIMMs add up to 80GB, not 79GB

**Comment by tomhughes** [comment]
Yes, it's a rounding error. The total comes from the total in /proc/meminfo I think which is often slightly lower than the physical RAM as it excludes odd bits that the BIOS prevents the kernel from using.

**Comment by tomhughes** [comment]
There is code which attempts to round to plausible sizes, but it's all very complicated due to the differences between disk sizes and memory sizes and all the different units that different bits of the system choose to report in...

**Comment by tomhughes** [comment]
So orm reports 82483572kB which is 78.662GB and we are effectively rounding to the nearest GB which is 79 as you've seen.

Now I could round to the nearest 4GB which would fix it, but we do still have a few machines to DIMMs smaller than that fitted... Alternatively we could just total the installed DIMMs but that would hide any errors if our DIMM enumeration is wrong...

**Comment by pnorman** [comment]
> 78.662GB

Wow, that's a lot of RAM taken by the system.

Perhaps "System Usable RAM: 78.7GB"?

**Comment by pnorman** [comment]
As we have it is good enough, given the constraints.
